### ISSUE TITLE
Please complete version

### ISSUE THREAD

**Issue by ldhpm2** [ViRb3/de4dot-cex#10]
The author of de4dot-cex software let me ask for the completed version with the exe file. Thank you very much

**Comment by ViRb3** [comment]
You can now find permanent releases here:
https://github.com/ViRb3/de4dot-cex/releases

**Comment by ldhpm2** [comment]
Thank you very much

Vào Th 6, 10 thg 1, 2020 vào lúc 23:58 Victor <notifications@github.com>
đã viết:
