### ISSUE TITLE
Can you deobfuscate this library?

### ISSUE THREAD

**Issue by simpo43** [ViRb3/de4dot-cex#12]
Sorry if off topic. But it’s very interesting how such a library can work at all. I have never seen such (corrupted?) Code. I wonder what obfuscator did this and whether it is possible to remove such obfuscation.
https://anonfile.com/V2P446gao8/Assembly-CSharp-firstpass_dll

**Comment by ViRb3** [comment]
Since Unity's Mono runtime is open-source, developers can afford to mess with it in all kinds of funny ways, for an example mixing the opcodes. The only way to figure that out for sure is to reverse engineer the (native) Mono runtime. However this is indeed off-topic, so I will close it.
