### ISSUE TITLE
Crypto obfuscator error

### ISSUE THREAD

**Issue by Laicfer** [ViRb3/de4dot-cex#16]
Hello, can u help me with this error ? i trying to deobfuscate an exe file but it doesnt work, i already use -d parameter to see wich one obfuscator it use and probably is crpyto obfuscator ( u can see it on logs error too )

WARNING: Found unknown resource encryption flags: 0x0A

Exceção Sem Tratamento: System.IO.InvalidDataException: O tamanho do bloco não corresponde ao seu complemento.
   em System.IO.Compression.Inflater.DecodeUncompressedBlock(Boolean& end_of_block)
   em System.IO.Compression.Inflater.Decode()
   em System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   em System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   em de4dot.code.deobfuscators.CryptoObfuscator.ResourceDecrypter.Decrypt(Stream resourceStream) na D:\a\de4dot-cex\de4dot-cex\de4dot.code\deobfuscators\CryptoObfuscator\ResourceDecrypter.cs:linha 371

anyway thanks by now.

**Comment by ViRb3** [comment]
Sorry, this project only supports ConfuserEx, not Crypto Obfuscator.
