### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by Imranjunnaid** [ViRb3/de4dot-cex#2]
dear am trying to build the source but getting alot many errors 
![image](https://user-images.githubusercontent.com/24642641/44763192-836ef880-ab63-11e8-97c8-bc9829daea12.png)
could you please help me out in this 
or can you share the build version as well

**Comment by ViRb3** [comment]
Try deleting the project and cloning the repo again. Also make sure you use the referenced dnlib submodule.

**Comment by Imranjunnaid** [comment]
dear

can you the the build version means release version with me, or any down
path from where i can download and test it
Imran Junnaid

**Comment by ViRb3** [comment]
Here you go:
https://github.com/ViRb3/de4dot-cex/releases/latest

**Comment by Imranjunnaid** [comment]
dear

thanks alot for your kind support


Imran Junnaid
