### ISSUE TITLE
can i decompile latest Agile.Net exe/dll file ?

### ISSUE THREAD

**Issue by kalpesh2804** [ViRb3/de4dot-cex#3]
I want to decompile latest agile.net protected file.

is it possible using this utility ?

**Comment by ViRb3** [comment]
You could try deobfuscating it with de4dot, but since this tool hasn't been updated in a while, chances are it won't work. Unfortunately I do not have the time to add support for any new obfuscators, but feel free to do that yourself, it's easier than you think.

**Comment by kalpesh2804** [comment]
Agile (clisecure) old version supported but new version not supported.

**Comment by ProjectManager717** [comment]
Agile (clisecure) old version supported but new version not supported.

This means you can decompile clisecure dll?

**Comment by ProjectManager717** [comment]
do you have any experience with this?
actually we are trying to decompile CliSecure dll and we are trying to find the developer for this... of course, we will surely pay for the correct developer.
I just want to discuss the project in more detail with you if you are interested... could you please let me know your skype id or email address? so I can contract you for quick discussing.

**Comment by kalpesh2804** [comment]
you can contact me on m email kalpesh204@yahoo.com

**Comment by ProjectManager717** [comment]
I sent email, but it shows error... what is your skype id?

**Comment by ProjectManager717** [comment]
when I hit your email it shows this error...https://prnt.sc/110z1bz
so let me know your skype id so I can contact you.

**Comment by kalpesh2804** [comment]
skype : kalpesh2804
