### ISSUE TITLE
Babel 7.0 - 8.0

### ISSUE THREAD

**Issue by Sybtek** [ViRb3/de4dot-cex#4]
hi can u update ur version of de4dot for new babel version?
old de4dot support only old versions of babel obfusicator

it would be great

**Comment by ViRb3** [comment]
I'm afraid I don't have the time to do that, this version is only for ConfuserEx. Good luck though, it's not as hard as you think!

**Comment by Sybtek** [comment]
Im not a dev so i cant do it by my self. I gonna pay when u can make it for me
